### ISSUE TITLE
Keycloak Authz Donation

### ISSUE THREAD

**Issue by robbert229** [react-keycloak/keycloak-ts#10]
Hello, recently I have been working on several apps where I needed to use the keycloak authz code, and ended up finding the official code unusable. I have since then re-implemented the same api, but in typescript, and using modern js features (such as the fetch api). I was hoping that I could find a good home for this code, and was hoping that I might be able to donate it to react-keycloak and keycloak-ts. Please let me know if you are open to this donation, and have a wonderful day! :)

**Comment by panz3r** [comment]
Hi @robbert229 ,

Thanks for contacting us, I think we can accept a PR related to this and that would be greatly appreciated.
